# Generated by Django 6.0.6 on 2026-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_aireview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aireview',
            old_name='review_text',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='aireview',
            name='overall_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aireview',
            name='structured_review',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
